#! /bin/sh
. panel_colors

num_mon=$(bspc query -M | wc -l)
PADDING="  "

while read -r line ; do
	case $line in
		DAY*)
			# date output
			date="$PADDING%{B$COLOR_DATETIME_BG}%{F$COLOR_DATETIME_FG}  ${line#???}$PADDING%{F-}%{B-}"
			# %{F#fabd2f}
			;;

		TIME*)
			# clock output
			clock="%{B$COLOR_DATETIME_BG}%{F$COLOR_DATETIME_FG}${line#????}$PADDING%{F-}%{B-}"
			;;

		BAT*)
			# battery percent output
			battery="$PADDING${line#???}$PADDING"
			;;

		VOL*)
			# alsa volume
			volume="$PADDING${line#???}$PADDING"
			;;

		WIRELESS*)
			# wifi link
			wifi="$PADDING%${line#????????}$PADDING"
			# wifi="$PADDING%{F#689d6a}${line#????????}$PADDING"
			;;

    EMAIL*)
        # email alerts
        email="$PADDING${line#?????}$PADDING"
        ;;

    MESSAGE*)
        # Weechat messages
        messages="$PADDING${line#???????}$PADDING"
        ;;

    NEWS*)
        # Newsbeuter articles
        news="$PADDING${line#????}$PADDING"
          ;;

		MUSIC*)
			# music info
			music="$PADDING${line#?????}$PADDING"
			;;

		RAM*)
			# ram output
			memory="$PADDING%{F#d3869b} ${line#???}$PADDING"
			;;

    CPU*)
			# cpu output
			cpu="$PADDING%{F#cc241d} ${line#???}%{F-}$PADDING"
			;;

		ROOT*)
			# disk output
			hddroot="$PADDING%{F#458588} root ${line#????}%{F-}$PADDING"
			;;

		DATA*)
			# disk output
			hdddata="$PADDING%{F#d79921} data ${line#????}%{F-}$PADDING"
			;;

# uncomment for window title support
#		TITLE*)
#			# xtitle output
#			title="${line#?????}$PADDING$PADDING"
#			;;

		W*)
			# bspwm internal state
			wm_infos=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					M*)
						# active monitor
						if [ $num_mon -gt 1 ] ; then
					    wm_infos="$wm_infos %{F$COLOR_ACTIVE_MONITOR_FG}%{B$COLOR_ACTIVE_MONITOR_BG}$PADDING${name}$PADDING%{B-}%{F-}  "
						fi
						;;
					m*)
						# inactive monitor
						if [ $num_mon -gt 1 ] ; then
					    wm_infos="$wm_infos %{F$COLOR_INACTIVE_MONITOR_FG}%{B$COLOR_INACTIVE_MONITOR_BG}$PADDING${name}$PADDING%{B-}%{F-}  "
						fi
						;;
					O*)
						# focused occupied desktop
						# wm_infos="${wm_infos}%{F$COLOR_FOCUSED_OCCUPIED_FG}%{B$COLOR_FOCUSED_OCCUPIED_BG}%{U$COLOR_FOREGROUND}$PADDING${name}$PADDING%{B-}%{F-}"
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_OCCUPIED_FG}%{B$COLOR_FOCUSED_OCCUPIED_BG}%{U$COLOR_FOREGROUND}%{+u}$PADDING${name}$PADDING%{-u}%{B-}%{F-}"
            ;;
					F*)
						# focused free desktop
						# wm_infos="${wm_infos}%{F$COLOR_FOCUSED_FREE_FG}%{B$COLOR_FOCUSED_FREE_BG}%{U$COLOR_FOREGROUND}$PADDING${name}$PADDING%{B-}%{F-}"
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_FREE_FG}%{B$COLOR_FOCUSED_FREE_BG}%{U$COLOR_FOREGROUND}%{+u}$PADDING${name}$PADDING%{-u}%{B-}%{F-}"
            ;;
					U*)
						# focused urgent desktop
						# wm_infos="${wm_infos}%{F$COLOR_FOCUSED_URGENT_FG}%{B$COLOR_FOCUSED_URGENT_BG}%{U$COLOR_FOREGROUND}$PADDING${name}$PADDING%{B-}%{F-}"
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_URGENT_FG}%{B$COLOR_FOCUSED_URGENT_BG}%{U$COLOR_FOREGROUND}%{+u}$PADDING${name}$PADDING%{-u}%{B-}%{F-}"
            ;;
					o*)
						# occupied desktop
				    wm_infos="${wm_infos}%{F$COLOR_OCCUPIED_FG}%{B$COLOR_OCCUPIED_BG}$PADDING${name}$PADDING%{B-}%{F-}"
						# wm_infos="${wm_infos}%{F$COLOR_OCCUPIED_FG}%{B$COLOR_OCCUPIED_BG}%{A:bspc desktop -f ${name}:}$PADDING${name}$PADDING%{A}%{B-}%{F-}"
						;;
					f*)
						# free desktop
						wm_infos="${wm_infos}%{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG}$PADDING${name}$PADDING%{B-}%{F-}"
						# wm_infos="${wm_infos}%{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG}%{A:bspc desktop -f ${name}:}$PADDING${name}$PADDING%{A}%{B-}%{F-}"
						;;
					u*)
						# urgent desktop
						wm_infos="${wm_infos}%{F$COLOR_URGENT_FG}%{B$COLOR_URGENT_BG}$PADDING${name}$PADDING%{B-}%{F-}"
						;;
				esac
				shift
			done
			;;
	esac
	printf "%s\n" "%{l}${wm_infos}${hddroot}${hdddata}${cpu}${memory}%{c}${music}%{r}${news}${messages}${email}${wifi}${volume}${battery}${date}${clock}"
done


#  bitcoin
#  bluetooth
#  git