#!/bin/sh
# PURPOSE : Symlink or Copy the dotfiles (*.symlink & *.copy) to ~/
# status: finished on 2016-02-05. @TODO: test on platforms other than Arch Linux
# location : $DOTREPO/install/link
# this script designed to be sourced with some inherited parameters or run with default ones
sourced () {
	([[ -n $ZSH_EVAL_CONTEXT && $ZSH_EVAL_CONTEXT =~ :file$ ]] || 
	 [[ -n $KSH_VERSION && $(cd "$(dirname -- "$0")" &&
	    printf '%s' "${PWD%/}/")$(basename -- "$0") != "${.sh.file}" ]] || 
	 [[ -n $BASH_VERSION && $0 != "$BASH_SOURCE" ]]) && return 1 || return 0
}

if sourced ; then
	echo $hello...
fi