#!/bin/sh
# purpose  : checked if sourced or run as sub-shell
# status   : finished on 2016-02-05.
# location : $DOTREPO/install/sourced
# this script designed to be sourced

sourced () {
	([[ -n $ZSH_EVAL_CONTEXT && $ZSH_EVAL_CONTEXT =~ :file$ ]] || 
	 [[ -n $KSH_VERSION && $(cd "$(dirname -- "$0")" &&
	    printf '%s' "${PWD%/}/")$(basename -- "$0") != "${.sh.file}" ]] || 
	 [[ -n $BASH_VERSION && $0 != "$BASH_SOURCE" ]]) && return 1 || return 0
}

if sourced ; then
	echo $hello...
fi